---
Name: Telkin
WURPLSVersion: '0.1'
#Version: '0.1' # TODO: Version number for the RPL
Freestanding: true
Initless: true
IncludeDirs:
    - ../include

    # TODO Libs (Tachyon handle these)
    - ../../../DynamicLibs/dynamic_libs/include
    - ../../../DynamicLibs/cafe_sdk/include
    
    #* Temp
    - ../../../headers
    - ../../../sead/engine/library/include

    #! std (Tachyon definitely handle these)
    - ../../../RedNewlib/abi
    - ../../../RedNewlib/c
    - ../../../RedNewlib/cxx

SourceDirs:
    - ../src

    # TODO Libs (Tachyon handle these)
    - ../../../DynamicLibs/dynamic_libs/src

Targets:
    Universal: ~
