name: Build (Cemu)

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Run generator
        run: python ./bootstrap/cemu/generate.py

      - name: Upload build artifacts (all branches)
        uses: actions/upload-artifact@v4
        with:
          name: ci-output-${{ github.ref_name }}
          path: ./out/
