name: Build (Aroma Plugin)

on:
  push:
    paths:
      - 'launcher/aroma'
  pull_request:
    paths:
      - 'launcher/aroma'

jobs:
  build-plugin:
    runs-on: ubuntu-latest
    name: Build plugin
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: false

    - name: Setup Docker
      run: docker build --tag plugin-image ./launcher/aroma

    - name: Build
      run: |
        docker run --rm \
          --name plugin-container \
          -v "${{ github.workspace }}:/github/workspace" \
          -w /github/workspace/launcher/aroma \
          plugin-image \
          make

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Telkin-loader.wps
        path: ${{ github.workspace }}/launcher/aroma/Telkin-loader.wps
        if-no-files-found: error
